FROM rutgerhofste/aqueduct30:v12

MAINTAINER Rutger Hofste <rutgerhofste@gmail.com>

RUN apt-get install libffi-dev libssl-dev python-dev python-pip -y

RUN pip install cryptography google-api-python-client earthengine-api

