FROM eboraas/jupyter
MAINTAINER Rutger Hofste <rutgerhofste@gmail.com>

RUN apt-get update
RUN apt-get install -y git

RUN git clone https://github.com/rutgerhofste/Aqueduct30Docker.git

RUN pip install boto3

RUN pip install pandas




